#!/usr/bin/python
#Problem 29!
#8th May 2008
#How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?
arr=[]
for a in range(2,101):
	for b in range(2,101):
		c=(a**b)
		if c not in arr:
			arr+=[c]

print len(arr)